appName: HouseHunter

pages:
  page_1:
    type: mieszkania
    market: rynek_wtorny
    url: "https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/mieszkanie/ikl,101.html?strona="
    filename: "mieszkania_rynek_wtorny.txt"
  page_2:
    type: mieszkania
    market: rynek_pierwotny
    url: "https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-pierwotny/mieszkanie/ikl,101.html?strona="
    filename: "mieszkania_rynek_pierwotny.txt"